In [1]:
import numpy as np
import sys

In [2]:
a = np.array([[11,22,33,44,55],[10,20,30,40,50]])
print(a)

[[11 22 33 44 55]
 [10 20 30 40 50]]


In [4]:
a.shape

(2, 5)

In [5]:
a[0,2]

33

In [6]:
a[1,-2]

40

In [7]:
a[0,:]

array([11, 22, 33, 44, 55])

In [8]:
a[:,0]

array([11, 10])

In [9]:
a[1,4]=99
print(a)

[[11 22 33 44 55]
 [10 20 30 40 99]]


In [10]:
a[:,2]=101
print(a)

[[ 11  22 101  44  55]
 [ 10  20 101  40  99]]


In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.full((2,4),99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [18]:
np.full((2,4),99,dtype='float32')

array([[99., 99., 99., 99.],
       [99., 99., 99., 99.]], dtype=float32)

In [19]:
np.random.rand(4,2)

array([[0.72035039, 0.07181257],
       [0.48913429, 0.80836612],
       [0.14621658, 0.99237281],
       [0.5329665 , 0.40503575]])

In [20]:
np.random.randint(10,size=(2,4))

array([[1, 4, 5, 0],
       [0, 7, 3, 4]])

In [21]:
np.random.randint(10,20,size=(2,4))

array([[11, 13, 18, 10],
       [10, 17, 19, 14]])

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
arr = np.array([1,2,3])
rp = np.repeat(arr,4)
print(rp)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [26]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [27]:
a+2

array([3, 4, 5, 6])

In [28]:
a-2

array([-1,  0,  1,  2])

In [29]:
a*2

array([2, 4, 6, 8])

In [30]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [32]:
a ** 2

array([ 1,  4,  9, 16])

In [33]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [34]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [35]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [37]:
a = np.ones((2,3))
print(a)

b=np.full((3,2),4)
print(b)

c=np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]
[[12. 12.]
 [12. 12.]]


In [38]:
c=np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [39]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.min(stats)

1

In [41]:
np.max(stats)

6

In [42]:
np.max(stats, axis=1)

array([3, 6])

In [43]:
np.max(stats, axis=0)

array([4, 5, 6])

In [44]:
pre = np.array([[1,2,3,4],[5,6,7,8]])
print(pre)

post = pre.reshape((1,8))
print(post)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [45]:
pre = np.array([[1,2,3,4],[5,6,7,8]])
print(pre)

post = pre.reshape((4,2))
print(post)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
pre = np.array([[1,2,3,4],[5,6,7,8]])
print(pre)

post = pre.reshape((2,2,2))
print(post)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [51]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
# upload data.txt file here first. Then "copy path" and paste it beneath
filedata = np.genfromtxt('/content/data',delimiter=',')
print(filedata)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  22.  33.  44.  55.  66.  77.  88.  99. 111.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]


In [81]:
filedata = filedata.astype('int32')
print(filedata)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  22  33  44  55  66  77  88  99 111]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [82]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False,  True,  True,  True,  True,
         True]])

In [83]:
filedata [filedata > 50]

array([ 55,  66,  77,  88,  99, 111,  60,  70,  80,  90, 100], dtype=int32)

In [84]:
np.any(filedata>50, axis=0)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [85]:
np.any(filedata>50, axis=1)

array([False,  True,  True])

In [86]:
((filedata>50)&(filedata<75))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True,  True, False, False, False,
        False],
       [False, False, False, False, False,  True,  True, False, False,
        False]])

In [87]:
~((filedata>50)&(filedata<75))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False,  True,  True,
         True]])